In [2]:
import gensim as gensim
import numpy as np
import torch

from nya_ml_research.config import DATA_PATH, MODELS_PATH
from nya_ml import embeddings

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
embedding = embeddings.get('ruwiki').load(MODELS_PATH / 'embeddings')

embedding

In [5]:
g: gensim.models.KeyedVectors = embedding.to_gensim()

In [6]:
g.key_to_index

{'xxxxxxxx_NUM': 0,
 'год_NOUN': 1,
 'xxxxxx_NUM': 2,
 'xxxxxxx_NUM': 3,
 'первый_ADJ': 4,
 'время_NOUN': 5,
 'человек_NOUN': 6,
 'introduction_PROPN': 7,
 'один_NUM': 8,
 'район_NOUN': 9,
 'мочь_VERB': 10,
 'стать_VERB': 11,
 'так_ADV': 12,
 'город_NOUN': 13,
 'другой_ADJ': 14,
 'область_NOUN': 15,
 'быть_VERB': 16,
 'новый_ADJ': 17,
 'два_NUM': 18,
 'перенаправление_NOUN': 19,
 'состав_NOUN': 20,
 'часть_NOUN': 21,
 'россия_PROPN': 22,
 'место_NOUN': 23,
 'также_ADV': 24,
 'являться_VERB': 25,
 'где_ADV': 26,
 'иметь_VERB': 27,
 'работа_NOUN': 28,
 'война_NOUN': 29,
 'самый_ADJ': 30,
 'уже_ADV': 31,
 'получить_VERB': 32,
 'второй_ADJ': 33,
 'день_NOUN': 34,
 'век_NOUN': 35,
 'еще_ADV': 36,
 'российский_ADJ': 37,
 'группа_NOUN': 38,
 'жизнь_NOUN': 39,
 'имя_NOUN': 40,
 'мир_NOUN': 41,
 'игра_NOUN': 42,
 'река_NOUN': 43,
 'более_ADV': 44,
 'сказать_VERB': 45,
 'русский_ADJ': 46,
 'говорить_VERB': 47,
 'находиться_VERB': 48,
 'советский_ADJ': 49,
 'государственный_ADJ': 50,
 'дело_NOUN'

In [7]:
# t.size()

In [8]:
from torch import nn

In [9]:
# e = nn.Embedding(num_embeddings=249333, embedding_dim=300, _weight=t)

In [10]:
# e(torch.tensor('привет'))

In [11]:
# from nya_ml.preprocessing.rusvectores import Tokenizer

In [12]:
# tokenizer.apply('привет всем ;;32;52;6221635%%%любителям пончиков')

In [13]:
# tokenizer.tokenize('привет всем ;;32;52;6221635%%%любителям пончиков')

In [15]:
from nya_ml.preprocessing.tagger import tag
tag('еще')

'ещё_ADVB'

# check

In [32]:
list(filter(lambda w: w.startswith('этот'), g.key_to_index.keys()))

['этот_NOUN', 'этот_PROPN', 'этот_ADJ', 'этот_VERB']

In [136]:
# tokenizer.apply('гитлер')

In [137]:
from nltk import RegexpTokenizer
import nltk

In [138]:
nltk.word_tokenize('привет всем ;;32;52;6221635%%%любителям пончиков', language='russian', preserve_line=False)

['привет',
 'всем',
 ';',
 ';',
 '32',
 ';',
 '52',
 ';',
 '6221635',
 '%',
 '%',
 '%',
 'любителям',
 'пончиков']

In [139]:
t = RegexpTokenizer('')

In [140]:
t.tokenize('привет всем ;;32;52;6221635%%%любителям пончиков')

['',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [141]:
'любителям_NOUN' in g.key_to_index

False

In [142]:
from nya_ml.preprocessing.tagger import Tagger

tokenize = lambda sent: list(map(Tagger().apply, nltk.word_tokenize(sent)))

In [143]:
tokenize('привет всем ;;32;52;6221635%%%любителям пончиков')

['привет_NOUN',
 'весь_ADJF',
 ';_X',
 ';_X',
 '32_X',
 ';_X',
 '52_X',
 ';_X',
 '6221635_X',
 '%_X',
 '%_X',
 '%_X',
 'любитель_NOUN',
 'пончик_NOUN']

In [144]:
from nya_ml.preprocessing.tokenizer import Tokenizer

In [145]:
from functools import partial

tokenizer = Tokenizer(tagger=Tagger(), key_to_index=g.key_to_index, index_to_key=g.index_to_key)

In [146]:
tokenizer.apply('привет всем ;;32;52;6221635%%%любителям пончиков')

[10769, 244476, 3281, 62853]

In [147]:
g.index_to_key[-1]

'людовикус_PROPN'

In [148]:
from torchdata.datapipes.iter import IterableWrapper, Mapper

In [163]:
data = [
    "У нас есть прекрасная история, как сдохнуть за неделю!!)",
    "я рааааааад,ведь сегодня впереди вся ночь,сериалы,фильмы,книга и кофе:) идеальная ночка:)",
    "Мне одному   напоминает дом-2? Путин делает реалити-шоу? O_o",
    "Выпилил powerpill и perl-xyne-arch из своего Арча, разработчик отказался от их поддержки, а жаль( #archlinux",
    "У нас есть прекрасная история, как сдохнуть за неделю!!)",
    "я рааааааад,ведь сегодня впереди вся ночь,сериалы,фильмы,книга и кофе:) идеальная ночка:)",
    "Мне одному   напоминает дом-2? Путин делает реалити-шоу? O_o",
    "Выпилил powerpill и perl-xyne-arch из своего Арча, разработчик отказался от их поддержки, а жаль( #archlinux",

]

In [164]:
processed = list(map(torch.tensor, map(tokenizer.apply, data)))

In [165]:
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import TensorDataset


In [166]:
padded = pad_sequence(processed, batch_first=True)

In [167]:
padded

tensor([[    67,    698,      0,      0,      0,      0],
        [   444,    762,     54,    129,   4581,  81529],
        [  1692,     55,      0,      0,      0,      0],
        [151935, 144004,   2910,    924,    614,      0],
        [    67,    698,      0,      0,      0,      0],
        [   444,    762,     54,    129,   4581,  81529],
        [  1692,     55,      0,      0,      0,      0],
        [151935, 144004,   2910,    924,    614,      0]])

In [168]:
ds = TensorDataset(padded)

In [169]:
ds.tensors

(tensor([[    67,    698,      0,      0,      0,      0],
         [   444,    762,     54,    129,   4581,  81529],
         [  1692,     55,      0,      0,      0,      0],
         [151935, 144004,   2910,    924,    614,      0],
         [    67,    698,      0,      0,      0,      0],
         [   444,    762,     54,    129,   4581,  81529],
         [  1692,     55,      0,      0,      0,      0],
         [151935, 144004,   2910,    924,    614,      0]]),)

In [176]:
from torchtext.vocab import vocab, GloVe

In [177]:
vocab()

.vector_cache\glove.840B.300d.zip:   0%|          | 4.71M/2.18G [00:03<25:32, 1.42MB/s]   


KeyboardInterrupt: 

In [205]:
from nltk import word_tokenize
from collections import Counter

v = vocab(g.key_to_index)
# v.insert_token('<unk>', 0)
# v.set_default_index(v['<unk>'])

In [206]:
v['людовикус_PROPN']

249331

In [191]:
v(['людовикус_PROPN', 'людовикус_PROPN', 's'])

[249332, 249332, 0]

In [170]:
from torch.utils.data import DataLoader

dl = DataLoader(ds, 2)

In [174]:
for s in dl:
    X, *y = s
    print(X)
    # print([c.size() for c in s])
    for x in X:
        print(x)
        print(tokenizer.unapply(x.tolist()))

tensor([[   67,   698,     0,     0,     0,     0],
        [  444,   762,    54,   129,  4581, 81529]])
tensor([ 67, 698,   0,   0,   0,   0])
['история', 'неделя', 'xxxxxxxx', 'xxxxxxxx', 'xxxxxxxx', 'xxxxxxxx']
tensor([  444,   762,    54,   129,  4581, 81529])
['ночь', 'сериал', 'фильм', 'книга', 'кофе', 'ночка']
tensor([[  1692,     55,      0,      0,      0,      0],
        [151935, 144004,   2910,    924,    614,      0]])
tensor([1692,   55,    0,    0,    0,    0])
['напоминать', 'делать', 'xxxxxxxx', 'xxxxxxxx', 'xxxxxxxx', 'xxxxxxxx']
tensor([151935, 144004,   2910,    924,    614,      0])
['выпилить', 'арча', 'разработчик', 'отказаться', 'поддержка', 'xxxxxxxx']
tensor([[   67,   698,     0,     0,     0,     0],
        [  444,   762,    54,   129,  4581, 81529]])
tensor([ 67, 698,   0,   0,   0,   0])
['история', 'неделя', 'xxxxxxxx', 'xxxxxxxx', 'xxxxxxxx', 'xxxxxxxx']
ERROR! Session/line number was not unique intensor([  444,   762,    54,   129,  4581, 81529])
['ноч

In [155]:
list(map((2).__sub__, list(torch.tensor([1, 2, 3]))))

[NotImplemented, NotImplemented, NotImplemented]

ERROR! Session/line number was not unique in database. History logging moved to new session 176


In [201]:
from nya_ml.preprocessing.tagger import tag

v = vocab(g.key_to_index)
v.insert_token('<unk>', 0)
v.set_default_index(v['<unk>'])

def tokenize(text: str):
    tokens = word_tokenize(text, language='russian')
    print(tokens)
    tokens = v([tag(token) for token in tokens])
    print(tokens)
    return tokens

In [31]:
tokenize('привет всем ;;32;52;6221635%%%любителям пончиков')

NameError: name 'tokenize' is not defined

In [211]:
import numpy as np

In [212]:
ebs = vocab(dict(enumerate(g.vectors)), min_freq=np.zeros(300))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [209]:
g.vectors.shape

(249333, 300)

In [ ]:
def

In [213]:
np.zeros(300)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.