In [5]:
import torch

In [7]:
%load_ext autoreload
%autoreload 2

# Tensor basics

In [16]:
x = torch.empty(3, 3, 3)

In [17]:
x

tensor([[[1.1112e-38, 1.0653e-38, 1.0194e-38],
         [9.8266e-39, 8.4490e-39, 9.2756e-39],
         [1.0837e-38, 9.9184e-39, 9.0000e-39]],

        [[1.0561e-38, 1.0653e-38, 4.1327e-39],
         [8.9082e-39, 9.8265e-39, 9.4592e-39],
         [1.0561e-38, 1.0653e-38, 1.0469e-38]],

        [[9.5510e-39, 1.0745e-38, 9.6429e-39],
         [1.0561e-38, 9.1837e-39, 1.0653e-38],
         [8.4490e-39, 9.1837e-39, 9.0919e-39]]])

In [19]:
torch.rand(3, 3, 3)

tensor([[[0.8283, 0.8937, 0.8049],
         [0.4298, 0.8923, 0.0081],
         [0.8531, 0.8020, 0.1262]],

        [[0.4975, 0.1207, 0.5062],
         [0.0601, 0.8827, 0.9817],
         [0.4055, 0.2056, 0.5245]],

        [[0.9776, 0.8585, 0.2853],
         [0.0512, 0.5207, 0.9325],
         [0.0630, 0.7000, 0.2093]]])

In [20]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
x = _

In [23]:
x.dtype

torch.float32

In [24]:
x = torch.ones(3, 3, dtype=torch.int32)

In [25]:
x.dtype

torch.int32

In [27]:
x.size()

torch.Size([3, 3])

In [28]:
x = torch.tensor([2.5, 67, 1])

In [29]:
x

tensor([ 2.5000, 67.0000,  1.0000])

In [30]:
x = torch.tensor([[2.5, 67], [1, 5]])

In [32]:
x

tensor([[ 2.5000, 67.0000],
        [ 1.0000,  5.0000]])

In [33]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [34]:
x + y

tensor([[0.8277, 1.3882],
        [0.6296, 1.3714]])

In [35]:
torch.add(x, y)

tensor([[0.8277, 1.3882],
        [0.6296, 1.3714]])

In [36]:
x.add_(y) # inplace

tensor([[0.8277, 1.3882],
        [0.6296, 1.3714]])

In [37]:
x

tensor([[0.8277, 1.3882],
        [0.6296, 1.3714]])

In [38]:
x.add(y)

tensor([[1.5386, 2.3069],
        [1.0543, 1.7694]])

In [39]:
x

tensor([[0.8277, 1.3882],
        [0.6296, 1.3714]])

In [40]:
torch.sub(x, y)

tensor([[0.1167, 0.4695],
        [0.2050, 0.9733]])

In [41]:
torch.mul(x, y)

tensor([[0.5884, 1.2753],
        [0.2674, 0.5459]])

In [42]:
x = torch.rand(5, 3)

In [44]:
x

tensor([[0.9076, 0.5621, 0.6932],
        [0.1850, 0.2643, 0.4251],
        [0.1417, 0.1369, 0.9144],
        [0.7118, 0.1640, 0.9065],
        [0.4925, 0.5739, 0.9831]])

In [46]:
x[:, 0]

tensor([0.9076, 0.1850, 0.1417, 0.7118, 0.4925])

In [47]:
x[0, :]

tensor([0.9076, 0.5621, 0.6932])

In [48]:
x[1, 1]

tensor(0.2643)

In [49]:
_.item()

0.26427221298217773

In [50]:
x = torch.rand(4, 4)

In [51]:
x

tensor([[0.1621, 0.2522, 0.1036, 0.1368],
        [0.7815, 0.8442, 0.5761, 0.7277],
        [0.1607, 0.6369, 0.3209, 0.7103],
        [0.6956, 0.4940, 0.8413, 0.7795]])

In [52]:
y = x.view(16)

In [53]:
y

tensor([0.1621, 0.2522, 0.1036, 0.1368, 0.7815, 0.8442, 0.5761, 0.7277, 0.1607,
        0.6369, 0.3209, 0.7103, 0.6956, 0.4940, 0.8413, 0.7795])

In [55]:
x.view(-1, 8)

tensor([[0.1621, 0.2522, 0.1036, 0.1368, 0.7815, 0.8442, 0.5761, 0.7277],
        [0.1607, 0.6369, 0.3209, 0.7103, 0.6956, 0.4940, 0.8413, 0.7795]])

In [56]:
_.size()

torch.Size([2, 8])

In [57]:
x

tensor([[0.1621, 0.2522, 0.1036, 0.1368],
        [0.7815, 0.8442, 0.5761, 0.7277],
        [0.1607, 0.6369, 0.3209, 0.7103],
        [0.6956, 0.4940, 0.8413, 0.7795]])

In [58]:
import numpy as np

In [59]:
x = torch.ones(5)

In [60]:
x

tensor([1., 1., 1., 1., 1.])

In [61]:
x.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [62]:
type(_)

numpy.ndarray

In [63]:
y = x.numpy()

In [64]:
x.add_(torch.rand(5))

tensor([1.2656, 1.6297, 1.0501, 1.2661, 1.1101])

In [65]:
y

array([1.2656357, 1.6297071, 1.0500726, 1.2660806, 1.1100625],
      dtype=float32)

In [66]:
x = np.ones(5)

In [67]:
x

array([1., 1., 1., 1., 1.])

In [68]:
y = torch.from_numpy(x)

In [69]:
y

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [71]:
y.add_(torch.ones(5))

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [72]:
x

array([2., 2., 2., 2., 2.])

In [73]:
x = torch.ones(5, requires_grad=True)

In [74]:
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

# Autograd

In [75]:
x = torch.randn(3)

In [76]:
x

tensor([ 0.4368, -0.3493, -0.5378])

In [80]:
x = torch.randn(3, requires_grad=True)

In [81]:
y = x + 2

In [82]:
y

tensor([1.4203, 2.0126, 3.1178], grad_fn=<AddBackward0>)

In [83]:
z = y * y * 2

In [84]:
z

tensor([ 4.0344,  8.1011, 19.4412], grad_fn=<MulBackward0>)

In [85]:
z = z.mean()

In [86]:
z

tensor(10.5256, grad_fn=<MeanBackward0>)

In [87]:
z.backward() # dz/dx

In [88]:
x.grad

tensor([1.8937, 2.6835, 4.1570])

In [90]:
x = torch.randn(3, requires_grad=True)
y = x + 2
z = y * y * 2
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)

In [91]:
x.grad

tensor([8.0334e-01, 1.5919e+01, 9.4448e-03])

In [92]:
# disable grad

In [ ]:
x.requires_grad_(False)
x = x.detach()
with torch.no_grad():
    ...

In [93]:
x

tensor([0.0084, 1.9797, 0.3612], requires_grad=True)

In [95]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.0084, 3.9797, 2.3612])


In [96]:
y = x + 2
y

tensor([2.0084, 3.9797, 2.3612], grad_fn=<AddBackward0>)

In [103]:
weights = torch.ones(4, requires_grad=True)

In [101]:
for epoch in range(2):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [104]:
optimizer = torch.optim.SGD(weights, lr=0.01)

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [105]:
optimizer.step()

NameError: name 'optimizer' is not defined

In [ ]:
optimizer.zero_grad()

# Backpropagation

In [107]:
x = torch.tensor(1.0)

In [108]:
y = torch.tensor(2.0)

In [109]:
w = torch.tensor(1.0, requires_grad=True)

In [110]:
# forward and compute loss
y_ = w * x
loss = (y_ - y) ** 2

In [111]:
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [112]:
# backward

In [113]:
loss.backward()

In [114]:
w.grad

tensor(-2.)

# Linear regression

## Manual

### Numpy

In [115]:
# f = w * x

In [116]:
# f = 2 * x

In [117]:
X = np.array([1, 2, 3, 4], dtype=np.float32)

In [127]:
Y = np.array([2, 4, 6, 8], dtype=np.float32)

In [131]:
w = 0.0

In [120]:
# prediction

In [121]:
def forward(x):
    return w * x

In [123]:
# loss
def loss(y_true, y_pred):
    return ((y_pred - y_true) ** 2).mean()

In [124]:
# grad
# MSE = 1/N * (w * x - y) ** 2
# dJ/dw = 1/N 2x (w * x - y)

In [126]:
def grad_fn(x, y, y_pred):
    return np.dot(2 * x, y_pred - y).mean()

In [132]:
print(f'Prediction before: f(5) = {forward(5):.3f}')
learning_rate = 0.01
epochs = 10

for epoch in range(epochs):
    # prediction
    y_pred = forward(X)
    # loss
    l = loss(Y, y_pred)
    #gradient
    dw = grad_fn(X, Y, y_pred)
    # update weights
    w -= learning_rate * dw
    if epoch % 2 == 0:
        print(f'epoch {epoch + 1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after: f(5) = {forward(5):.3f}')

Prediction before: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 3: w = 1.872, loss = 0.76800019
epoch 5: w = 1.980, loss = 0.01966083
epoch 7: w = 1.997, loss = 0.00050331
epoch 9: w = 1.999, loss = 0.00001288
Prediction after: f(5) = 9.999


### Torch

In [145]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)
w = torch.tensor(0.0, requires_grad=True, dtype=torch.float32)


# prediction
def forward(x):
    return w * x


# loss
def loss(y_true, y_pred):
    return ((y_pred - y_true) ** 2).mean()


In [146]:

print(f'Prediction before: f(5) = {forward(5):.3f}')
learning_rate = 0.01
epochs = 1000

for epoch in range(epochs):
    # prediction
    y_pred = forward(X)
    # loss
    l = loss(Y, y_pred)
    #gradient
    l.backward()
    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad

    # zero gradient
    w.grad.zero_()

    if epoch % 100 == 0:
        print(f'epoch {epoch + 1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after: f(5) = {forward(5):.3f}')

Prediction before: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 101: w = 2.000, loss = 0.00000000
epoch 201: w = 2.000, loss = 0.00000000
epoch 301: w = 2.000, loss = 0.00000000
epoch 401: w = 2.000, loss = 0.00000000
epoch 501: w = 2.000, loss = 0.00000000
epoch 601: w = 2.000, loss = 0.00000000
epoch 701: w = 2.000, loss = 0.00000000
epoch 801: w = 2.000, loss = 0.00000000
epoch 901: w = 2.000, loss = 0.00000000
Prediction after: f(5) = 10.000


### PyTorch model

In [147]:
import torch.nn as nn

In [152]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32).view(-1, 1)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32).view(-1, 1)

test = torch.tensor([5], dtype=torch.float32)

n_samples, n_features = X.shape

model = nn.Linear(in_features=n_features, out_features=n_features)

In [153]:
print(f'Prediction before: f(5) = {model.forward(test).item():.3f}')

learning_rate = 0.01
epochs = 1000
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    # prediction
    y_pred = model.forward(X)
    # loss
    l = loss(Y, y_pred)
    #gradient
    l.backward()
    # update weights
    optimizer.step()
    # zero gradient
    optimizer.zero_grad()

    if epoch % 100 == 0:
        w, b = model.parameters()
        print(f'epoch {epoch + 1}: w = {w[0][0].item():.3f}, loss = {l:.8f}')

print(f'Prediction after: f(5) = {model.forward(test).item():.3f}')

Prediction before: f(5) = 2.234
epoch 1: w = 0.532, loss = 16.13908005
epoch 101: w = 1.719, loss = 0.11439715
epoch 201: w = 1.792, loss = 0.06280270
epoch 301: w = 1.846, loss = 0.03447798
epoch 401: w = 1.886, loss = 0.01892798
epoch 501: w = 1.915, loss = 0.01039124
epoch 601: w = 1.937, loss = 0.00570467
epoch 701: w = 1.954, loss = 0.00313179
epoch 801: w = 1.966, loss = 0.00171932
epoch 901: w = 1.975, loss = 0.00094388
Prediction after: f(5) = 9.961


### Custom model

In [154]:
class Linear(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Linear, self).__init__()

        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.lin(x)


In [155]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32).view(-1, 1)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32).view(-1, 1)

test = torch.tensor([5], dtype=torch.float32)

n_samples, n_features = X.shape

# model = nn.Linear(in_features=n_features, out_features=n_features)
model = Linear(n_features, n_features)
print(f'Prediction before: f(5) = {model.forward(test).item():.3f}')

learning_rate = 0.01
epochs = 1000
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    # prediction
    y_pred = model.forward(X)
    # loss
    l = loss(Y, y_pred)
    #gradient
    l.backward()
    # update weights
    optimizer.step()
    # zero gradient
    optimizer.zero_grad()

    if epoch % 100 == 0:
        w, b = model.parameters()
        print(f'epoch {epoch + 1}: w = {w[0][0].item():.3f}, loss = {l:.8f}')

print(f'Prediction after: f(5) = {model.forward(test).item():.3f}')

Prediction before: f(5) = -3.208
epoch 1: w = -0.203, loss = 53.35339737
epoch 101: w = 1.844, loss = 0.03552473
epoch 201: w = 1.884, loss = 0.01950266
epoch 301: w = 1.914, loss = 0.01070674
epoch 401: w = 1.936, loss = 0.00587786
epoch 501: w = 1.953, loss = 0.00322686
epoch 601: w = 1.965, loss = 0.00177152
epoch 701: w = 1.974, loss = 0.00097253
epoch 801: w = 1.981, loss = 0.00053391
epoch 901: w = 1.986, loss = 0.00029311
Prediction after: f(5) = 9.978


In [156]:
from sklearn import datasets
import matplotlib.pyplot as pl

In [157]:
X_np, y_np = datasets.make_regression(n_samples=100, n_features=1, noise=20, random_state=1)

In [158]:
X = torch.from_numpy(X_np.astype(np.float32))
y = torch.from_numpy(y_np.astype(np.float32))

In [159]:
y = y.view(-1, 1)

In [160]:
n_samples, n_features = X.shape

In [161]:
input_size = n_features
output_size = n_features

In [162]:
model = nn.Linear(input_size, output_size)

In [163]:
criterion = nn.MSELoss()

In [ ]:
optimizer = torch.optim.SGD(model.)